[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
cash-app = "Ekis1DgPsw7wAkWF9x28ziUeZp6vjhEQ9J4ikdMNJEWZ"
game = "CHZxZuE6fdPQAywgCRVp1wSJZbrqBczvo7VjFMCkkL4y"
hello_anchor = "2RgBM5i2YBy6kSZB6vtwbPdk7QzRCyim6QqsFdc7cRsc"
journal = "BNrXDLHnCC5aPZNoZvXi2JkbtejhvaCLQdJ4ddSNLBpw"

[programs.localnet]
cash-app = "Ekis1DgPsw7wAkWF9x28ziUeZp6vjhEQ9J4ikdMNJEWZ"
cpi_sol_splitter = "BF6hw3z49np3tQyQpnWDgb1yeKQY13Kz4YHB3BUcktHF"
energy_game = "7Nbobyn51AfuMFvzuc4mrRJWVzqWyyqoNnRhoB12xAW5"
game = "CHZxZuE6fdPQAywgCRVp1wSJZbrqBczvo7VjFMCkkL4y"
hello_anchor = "2RgBM5i2YBy6kSZB6vtwbPdk7QzRCyim6QqsFdc7cRsc"
journal = "BNrXDLHnCC5aPZNoZvXi2JkbtejhvaCLQdJ4ddSNLBpw"
points = "6GXHmCevpf1PK243z5BRznzGf3E3ua7VpVHE461c8ydG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/game.ts"
