[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
game = "CHZxZuE6fdPQAywgCRVp1wSJZbrqBczvo7VjFMCkkL4y"
hello_anchor = "2RgBM5i2YBy6kSZB6vtwbPdk7QzRCyim6QqsFdc7cRsc"

[programs.localnet]
cash-app = "Ekis1DgPsw7wAkWF9x28ziUeZp6vjhEQ9J4ikdMNJEWZ"
game = "7xpDxfrSrqREcPeFTnSUjWNKgrosuom55U8NxzctVFda"
hello_anchor = "5U3WeRHLRDq57Kdq2twZQrkgz4fMGvAqbZQjKWPAGiAU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/game.ts"
